stages:
  # tests, linting, formatting, build
  - deploy

# build docs
pages:
  stage: deploy

  image:
    name: rust:latest
    entrypoint: ['']

  script:
    - cargo doc --no-deps

  artifacts:
    paths:
      - ./target/doc/

    # when: always
    # expire_in: 3 week

    # exclude:
    #   - *.o

  rules:
    # - when: always

    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: manual
